[dependencies]
base = "https://github.com/dfinity/motoko-base#moc-0.10.1@80ededb39954739b18b88fc0e5561264003cf9ab"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc1-mo = "0.0.10"
icrc2-mo = "0.0.8"
icrc3-mo = "0.2.3"
icrc4-mo = "0.0.1"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "icrc-fungible"
version = "0.0.2"
description = "ICRC1, ICRC2, and ICRC3 fungible token for motoko"
repository = "hhttps://github.com/PanIndustrial-Org/ICRC_fungible"
keywords = [ "icrc2", "icrc1", "icrc3", "fungible", "token", "standard" ]
