[dependencies]
base = "0.11.0"
icrc1-mo = "0.0.16"
icrc2-mo = "0.0.16"
icrc3-mo = "0.3.5"
icrc4-mo = "0.0.16"
ic-certification = "0.1.3"
class-plus = "0.0.1"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "icrc-fungible"
version = "0.0.6"
description = "ICRC1, ICRC2, ICRC3, ICRC4, and ICRC10 fungible token for motoko"
repository = "https://github.com/PanIndustrial-Org/ICRC_fungible"
keywords = [
  "icrc2",
  "icrc1",
  "icrc3",
  "icrc4",
  "icrc10",
  "fungible",
  "token",
  "standard"
]

[toolchain]
moc = "0.14.14"
